- name: start-ec2
  ec2:
    key_name: devops-toolkit
    region: us-east-1
    instance_type: m3.medium
    image: ami-d15a75c7 
    spot_price: 0.03
    spot_wait_timeout: 600
    spot_launch_group: devops-toolkit
    wait: yes
    group: devops-toolkit-2
    exact_count: "{{ machines | map(attribute='count') | map('int') | sum(start=0) }}"
    vpc_subnet_id: subnet-6d1e9134
    assign_public_ip: yes
    instance_tags:
      devops_toolkit: worker
    count_tag:
      devops_toolkit: worker
  register: ec2

- debug: msg="{{ec2.tagged_instances}}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 0
    timeout: 320
    state: started
  with_items: 
    - "{{ ec2.tagged_instances }}"

- name: create seq for names
  set_fact:
    zipped_names: "{{ machines|flat_list_group_name }}"

- name: Change Name tag to reflect number when count > 1
  ec2_tag:
    region: us-east-1
    resource: "{{ item.0.id }}"
    state: present
    tags:
      Name: "{{ item.1['name'] }}"
      role: "{{ item.1['role']}}"
  with_together:
    - "{{ ec2.tagged_instances }}"
    - "{{ zipped_names }}"

# - name: refresh inventory when re tagging multiple instances
#   meta: refresh_inventory

- name: Add new instance to group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: "{{ item.tags.role }}"
  with_items: 
    - "{{ ec2.tagged_instances }}"

