- name: start-ec2
  ec2:
    key_name: devops-toolkit
    region: us-east-1
    instance_type: m3.medium
    image: ami-d15a75c7 
    spot_price: 0.03
    spot_wait_timeout: 600
    spot_launch_group: devops-toolkit
    wait: yes
    group: devops-toolkit-2
    exact_count: "{{ count_hosts | default(1) }}"
    vpc_subnet_id: subnet-6d1e9134
    assign_public_ip: no
    instance_tags:
      Name: "{{ EC2_NAME_TAG }}"
      role: "{{ EC2_ROLE }}"
      devops_toolkit: ''
    count_tag:
      role: "{{ EC2_ROLE }}"
  register: ec2

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.private_ip }}"
    port: 22
    delay: 0
    timeout: 320
    state: started
  with_items: 
    - "{{ec2.tagged_instances}}"

- name: Change Name tag to reflect number when count > 1
  ec2_tag:
    region: us-east-1
    resource: "{{ item[1].id }}"
    state: present
    tags:
      Name: "{{ EC2_NAME_TAG}}-{{ item[0] }}"
  with_indexed_items:
    - "{{ec2.tagged_instances}}"
  when: (count_hosts | default(1)) > 1

- name: Add new instance to group
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: "{{ EC2_ROLE }}"
  with_items: 
    - "{{ec2.tagged_instances}}"
