version: '3.3'

services:

  cd:
    build:
      context: ./continuous-delivery
    networks:
      devops:
        ipv4_address: 10.100.198.220
    command: ['sleep', 'infinity']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/home/dt/work

  prod:
    build:
      context: ./prod
    networks:
      devops:
        ipv4_address: 10.100.198.201
    command: ['sleep', 'infinity']

  registry:
    image: registry:2
    volumes:
      - /data/docker-registry:/var/lib/registry/docker/registry
      - /data/docker-registry/conf:/conf
    ports:
      - 5000:5000
    networks:
      devops:
        ipv4_address: 10.100.198.200
  registry-mirror:
    image: registry:2
    volumes:
      - /data/docker-registry-mirror:/var/lib/registry/docker/registry
      - /data/docker-registry-mirror/conf:/conf
      - ./continuous-delivery:/conf
    ports:
      - 5001:5000
    networks:
      devops:
        ipv4_address: 10.100.198.221
    command: ['serve', '/conf/mirror-config.yml']

networks:
  devops:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.0.0/16

