- name: gather facts
  setup:
  tags: [always]

- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"

# dynamically set consul_extra
- name: Set consul_extra if host is consul server
  set_fact:
    consul_extra: -server -bootstrap 
  when: ec2_tag_Name == "serv-disc-0"

- name: Is running
  shell: "kill -9 $(pidof consul); nohup consul agent {{ consul_extra }} \
    -ui \
    -data-dir /data/consul/data \
    -config-dir /data/consul/config \
    -node={{ ec2_tag_Name }} \
    -bind={{ ansible_default_ipv4.address }} \
    -client=0.0.0.0 \
    >{{ logs_dir }}/consul.log 2>&1 &"

- name: Has joined
  shell: consul join {{ groups['consul_server'][0] }}
  when: ec2_tag_Name != "serv-disc-0"
