- name: gather facts
  setup:
  tags: [registrator]

- name: debug
  debug: msg="-ip {{ ansible_default_ipv4.address }} {{ registrator_protocol }}://{{ ansible_default_ipv4.address }}:{{ registrator_port }}"
  tags: [registrator]

- name: Container is running
  docker_container:
    name: "{{ registrator_name }}"
    image: gliderlabs/registrator
    recreate: yes
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ ec2_tag_Name }}"
    command: -ip {{ ansible_default_ipv4.address }} {{ registrator_protocol }}://{{ ansible_default_ipv4.address }}:{{ registrator_port }}
  tags: [registrator]
