- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
    owner: ubuntu
  with_items: "{{ directories }}"
  tags: [haproxy]

- name: Files are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ files }}"
  register: result
  tags: [haproxy]

- name: Container is running
  docker_container:
    image: million12/haproxy
    name: haproxy
    state: started
    ports: "{{ ports }}"
    recreate: yes
    capabilities: NET_ADMIN
    volumes: /data/haproxy/config/:/etc/haproxy/
  tags: [haproxy]
