- name: Debian apt key for docker
  command: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg'
  register: docker_key

- name: Add to keyring
  apt_key:
    data: "{{docker_key.stdout}}"
    state: present

- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ debian_version }} stable'
    update_cache: yes
    state: present
  tags: [docker]

- name: Debian Docker is present
  apt:
    name: docker-ce
    state: latest
    force: yes
  tags: [docker]

- name: Debian python-pip is present
  apt:
    name: python-pip
    state: present
    force: yes
  tags: [docker]

- name: Debian docker is present
  pip:
    name: docker
    state: present
  tags: [docker]

- name: Debian files are present
  template:
    src: "{{ docker_cfg }}"
    dest: "{{ docker_cfg_dest }}"
  register: copy_result
  tags: [docker]

- name: Add host to docker service command
  replace:
    regexp: ExecStart=/usr/bin/dockerd .*
    replace: ExecStart=/usr/bin/dockerd -H fd:// -H tcp:0.0.0.0:2375
    path: /lib/systemd/system/docker.service

- name: Debian Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed and is_systemd is defined
  tags: [docker]

- name: ubuntu user is added to the docker group
  user:
    name: ubuntu 
    group: docker
  register: user_result
  tags: [docker]

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
  tags: [docker]

- name: DockerUI is running
  docker_container:
    image: uifd/ui-for-docker
    name: dockerui
    ports: 9000:9000
    privileged: yes
    restart: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  when: not skip_ui is defined
  tags: [docker]
