- hosts: localhost
  remote_user: ubuntu
  vars:
    - EC2_NAME_TAG: cd
    - EC2_ROLE: cd
  roles:
    - spot-ec2
  tags: [always]

- hosts: cd
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: install python-minimal
    raw: sudo apt-get -y update; sudo apt-get -y install python-minimal
    retries: 3
    ignore_errors: yes
  roles:
    - common
    - docker
    - docker-compose
    - docker-flow
    - consul-template
    - registry
  tags: [cd,common,docker,registry]
