- hosts: tag_role_serv_disc
  remote_user: ubuntu
  tags:
    registrator_protocol: consul
    registrator_port: 8500
    registrator_name: registrator-consul
  roles:
    - registrator
    - consul
  tags: [consul]
