- hosts: localhost
  remote_user: ubuntu
  serial: 1
  vars:
    - EC2_NAME_TAG: 'serv-disc'
    - EC2_ROLE: 'etcd'
    - count_hosts: 3
  roles:
    - spot-ec2

- hosts: etcd
  remote_user: ubuntu
  serial: 1
  gather_facts: no
  pre_tasks:
  - name: install python-minimal
    raw: sudo apt-get -y install python-minimal
  roles:
    - common
    - etcd
