- hosts: localhost
  remote_user: ubuntu
  vars:
    - EC2_NAME_TAG: serv-disc
    - EC2_ROLE: serv-disc
    - count_hosts: 3
  roles:
    - spot-ec2
  tags: [etcd]

- hosts: ec2_tag_role_serv_disc
  remote_user: ubuntu
  gather_facts: no
  roles:
    - common
    - etcd
