- hosts: localhost
  remote_user: ubuntu
  serial: 1
  vars:
    - EC2_NAME_TAG: 'devops-toolkit-prod'
    - EC2_ROLE: 'prod'
  roles:
    - spot-ec2

- hosts: prod
  remote_user: ubuntu
  serial: 1
  gather_facts: no
  pre_tasks:
  - name: install python-minimal
    raw: sudo apt-get -y install python-minimal
  roles:
    - common
    - docker

