- hosts: ec2_tag_role_serv_disc
  remote_user: ubuntu
  tasks:
    - name: set first to be the console_server
      add_host:
        hostname: "{{ ansible_default_ipv4.address }}"
        groupname: consul_server
      when: ec2_tag_Name == "serv-disc-0"
  tags: [consul]

- hosts: ec2_tag_role_serv_disc
  remote_user: ubuntu
  serial: 1
  vars:
    - registrator_name: registrator-consul
    - registrator_protocol: consul
    - registrator_port: 8500
  roles:
    - consul
    - consul-template
    - registrator
  tags: [consul]
