- hosts: localhost
  remote_user: ben
  become: no
  roles:
    - spot-ec2
  tasks:
  - name: write vars
    template: 
      src: variables.j2
      dest: /tmp/ansible-variables.txt

- hosts: tag_devops_toolkit_worker
  remote_user: ubuntu
  gather_facts: no
  tasks:
  - name: install python-minimal
    raw: test -e /usr/bin/python || (apt -y update && apt -y install python-minimal python-pip)
    register: installed_python
    until: installed_python.rc == 0
    changed_when: 
      - installed_python.stdout != ""
      - installed_python.stdout != "\r\n"
    ignore_errors: yes
  - name: install boto and boto3 
    raw: pip install boto boto3
  tags: [pymin]

- hosts: tag_devops_toolkit_worker
  remote_user: ubuntu
  roles:
    - common
    - openvpn-client

# - include: cd.yml
#   tags: [cd, always]
#  
# - include: prod.yml
#   tags: [prod, always]
#
# - include: serv-disc.yml
#   tags: [serv-disc, always]
#
# - include: registrator-etcd.yml
#   tags: [serv-disc,docker]  
#
# - include: registrator.yml
#   tags: [serv-disc,consul]
#
# write hosts file on all devops hosts
# - hosts: localhost:tag_devops_toolkit*
#   remote_user: ubuntu
#   tags: [hostsfile,always]
#   tasks:
#   - name: add hosts to hosts file
#     lineinfile:
#       insertafter: "127\\.0\\.0\\.1 .*"
#       path: "/etc/hosts"
#       state: absent
#       regexp: ".*{{hostvars[item].ec2_tag_Name }}$"
#     with_items: "{{ groups['vpc_id_vpc_460b5423'] }}"
#   - name: add hosts to hosts file
#     lineinfile:
#       insertafter: "127\\.0\\.0\\.1 .*"
#       path: "/etc/hosts"
#       regexp: ".*{{hostvars[item].ec2_tag_Name }}$"
#       line: "{{ hostvars[item].ec2_private_ip_address }} {{ hostvars[item].ec2_tag_Name }}"
#     with_items: "{{ groups['vpc_id_vpc_460b5423'] }}"
#   - name: remove previous 'known_hosts' file in home directory
#     file:
#       path: /home/ubuntu/.ssh/known_hosts
#       state: absent
