- hosts: localhost
  remote_user: ubuntu
  become: no
  roles:
    - spot-ec2
  tasks:
  - name: write vars
    template: 
      src: variables.j2
      dest: /tmp/ansible-variables.txt

- hosts: tag_devops_toolkit_worker
  remote_user: ubuntu
  gather_facts: no
  tasks:
  - name: install python-minimal
    raw: test -e /usr/bin/python || (apt -y update && apt -y install python-minimal python-pip)
    register: installed_python
    until: installed_python.rc == 0
    changed_when: 
      - installed_python.stdout != ""
      - installed_python.stdout != "\r\n"
    ignore_errors: yes
  - name: install boto and boto3 
    raw: pip install boto boto3
  tags: [pymin]

# write hosts file on all devops hosts
- hosts: tag_devops_toolkit*
  remote_user: ubuntu
  tags: [hostsfile,always]
  tasks:
  - name: write vars
    template: 
      src: variables.j2
      dest: /tmp/ansible-variables.txt
  - name: add hosts to hosts file
    lineinfile:
      insertafter: "127\\.0\\.0\\.1 .*"
      path: "/etc/hosts"
      state: absent
      regexp: ".*{{ item.value['ec2_tag_Name'] }}$"
    with_dict: "{{ hostvars }}"
  - name: add hosts to hosts file
    lineinfile:
      insertafter: "127\\.0\\.0\\.1 .*"
      path: "/etc/hosts"
      regexp: ".*{{item.value['ec2_tag_Name'] }}$"
      line: "{{ item.value['ec2_private_ip_address'] }} {{ item.value['ec2_tag_Name'] }}"
    with_dict: "{{ hostvars }}"
  - name: remove previous 'known_hosts' file in home directory
    file:
      path: /home/ubuntu/.ssh/known_hosts
      state: absent

- hosts: tag_devops_toolkit_worker
  remote_user: ubuntu
  roles:
    - docker
    - common
    # - openvpn-client
  tags: [docker]

- include: serv-disc.yml
- include: registrator.yml
- include: cd.yml
  tags: [docker]
- include: prod.yml


# - include: registrator-etcd.yml
#   tags: [serv-disc,docker]  

