- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Get instance ids
      ec2_remote_facts:
        region: us-east-1
        filters:
          "tag:devops_toolkit": ""
          "tag:role": ['cd', 'prod', 'etcd']
      register: ec2
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: us-east-1
        instance_id: "{{ item.id }}"
      with_items: "{{ ec2.instances }}"
